// Registry of code-defined video templates.
//
// Templates live in /remotion/templates/<slug>/. Each entry here describes
// the UI side (slots, inputs, preview/thumbnail URLs) plus dimensions used
// by the renderer. The Remotion component is the source of truth for the
// actual motion — keep these fields in sync with the composition's props.

export type SlotKind = "video";

export interface TemplateSlot {
  id: string;          // matches a Remotion prop, e.g. "clip1Url"
  label: string;       // shown above the uploader
  kind: SlotKind;
  maxSeconds: number;  // we'll trim longer clips later; informational for now
}

export interface TemplateTextInput {
  id: string;          // matches a Remotion prop, e.g. "headline"
  label: string;
  maxChars: number;
  placeholder?: string;
}

export interface VideoTemplate {
  id: string;
  name: string;
  description: string;
  category: "reels";
  fps: number;
  width: number;
  height: number;
  durationInFrames: number;
  slots: TemplateSlot[];
  textInputs: TemplateTextInput[];
  // Pre-rendered preview shown in the gallery card. Generated by
  // `npx tsx scripts/render-previews.ts` into /public/template-previews/.
  previewUrl?: string;
  // Static thumbnail (rarely used; previewUrl is preferred when available).
  thumbnailUrl?: string;
}

export const TEMPLATES: VideoTemplate[] = [
  {
    id: "beat-drop-3clip",
    name: "Beat Drop · 3 Clips",
    description:
      "Three quick cuts with a zoom-in and flash transitions. Headline lands on the last beat.",
    category: "reels",
    fps: 30,
    width: 1080,
    height: 1920,
    durationInFrames: 180,
    previewUrl: "/template-previews/beat-drop-3clip.mp4",
    slots: [
      { id: "clip1Url", label: "Clip 1", kind: "video", maxSeconds: 2 },
      { id: "clip2Url", label: "Clip 2", kind: "video", maxSeconds: 2 },
      { id: "clip3Url", label: "Clip 3", kind: "video", maxSeconds: 2 },
    ],
    textInputs: [
      { id: "headline", label: "Headline", maxChars: 60, placeholder: "Make it pop" },
    ],
  },
  {
    id: "slow-zoom",
    name: "Slow Zoom · 1 Clip",
    description:
      "Cinematic slow zoom with a fade-in headline. Drop in one clip and we'll do the rest.",
    category: "reels",
    fps: 30,
    width: 1080,
    height: 1920,
    durationInFrames: 180,
    previewUrl: "/template-previews/slow-zoom.mp4",
    slots: [
      { id: "clipUrl", label: "Your clip", kind: "video", maxSeconds: 6 },
    ],
    textInputs: [
      { id: "headline", label: "Headline", maxChars: 40, placeholder: "Sit with it" },
      { id: "subtitle", label: "Subtitle", maxChars: 80, placeholder: "A slower kind of scroll" },
    ],
  },
  {
    id: "before-after",
    name: "Before / After · 2 Clips",
    description:
      "Classic transformation reel. Two clips, a sharp swipe transition, big BEFORE/AFTER labels.",
    category: "reels",
    fps: 30,
    width: 1080,
    height: 1920,
    durationInFrames: 180,
    previewUrl: "/template-previews/before-after.mp4",
    slots: [
      { id: "beforeUrl", label: "Before clip", kind: "video", maxSeconds: 3 },
      { id: "afterUrl",  label: "After clip",  kind: "video", maxSeconds: 3 },
    ],
    textInputs: [],
  },
  {
    id: "countdown",
    name: "Countdown · 3 Clips",
    description:
      "Three clips with giant 3-2-1 numbers, then a headline drop. Great for top-3 lists.",
    category: "reels",
    fps: 30,
    width: 1080,
    height: 1920,
    durationInFrames: 210,
    previewUrl: "/template-previews/countdown.mp4",
    slots: [
      { id: "clip1Url", label: "Clip 3", kind: "video", maxSeconds: 2 },
      { id: "clip2Url", label: "Clip 2", kind: "video", maxSeconds: 2 },
      { id: "clip3Url", label: "Clip 1", kind: "video", maxSeconds: 2 },
    ],
    textInputs: [
      { id: "headline", label: "Final headline", maxChars: 30, placeholder: "Go" },
    ],
  },
  {
    id: "split-screen",
    name: "Split Screen · 2 Clips",
    description:
      "Two clips stacked top/bottom, framed text in the middle. Perfect for comparisons.",
    category: "reels",
    fps: 30,
    width: 1080,
    height: 1920,
    durationInFrames: 180,
    previewUrl: "/template-previews/split-screen.mp4",
    slots: [
      { id: "topUrl",    label: "Top clip",    kind: "video", maxSeconds: 6 },
      { id: "bottomUrl", label: "Bottom clip", kind: "video", maxSeconds: 6 },
    ],
    textInputs: [
      { id: "headline", label: "Center label", maxChars: 20, placeholder: "VS" },
    ],
  },
];

export function getTemplate(id: string): VideoTemplate | undefined {
  return TEMPLATES.find((t) => t.id === id);
}
